# Assignment# 2

In [9]:
import pandas as pd
df = pd.read_csv('data.csv')
list = df['X'].tolist()
size = len(df['X'])
def calculatedistance(cp1, cp2, datalist, si):
    c1_col = [] 
    c2_col = [] 
    for i in range(0, si):
        c1_col.append(abs(int(datalist[i] - cp1)))
        c2_col.append(abs(int(datalist[i] - cp2)))
    return (c1_col, c2_col)

def checkc1c2(x, y):
    if x < y:
        return 1
    elif y < x:
        return 2
    elif x == y:
        return 3
import random
centralpoint1 = []
centralpoint2 = []
letter = 'A'
precheck = []
currcheck = []
check = False
c1col = []
c2col = []
c1 = int(random.choice(list))
centralpoint1.append(c1)
c2 = int(random.choice(list))
centralpoint2.append(c2)
(c1col, c2col) = calculatedistance(c1, c2, list, size)
for i in range(0, size):
    condition = checkc1c2(c1col[i], c2col[i])
    if condition == 1:
        currcheck.append('c1isless')
    elif condition == 2:
        currcheck.append('c2isless')
    elif condition == 3:
        currcheck.append('bothequal')
precheck = currcheck
df[letter + 'C' + str(1)] = c1col
df[letter + 'C' + str(2)] = c2col 
letter = chr(ord(letter) + 1)
while True:
    c1col = []
    c2col = []
    c1 = random.choice(list)
    centralpoint1.append(c1)
    c2 = random.choice(list)
    centralpoint2.append(c2)
    (c1col, c2col) = calculatedistance(c1, c2, list, size)
    currcheck = []
    for i in range(0, size):
        condition = checkc1c2(c1col[i], c2col[i])
        if condition == 1:
            currcheck.append('c1isless')
        elif condition == 2:
            currcheck.append('c2isless')
        elif condition == 3:
            currcheck.append('bothequal')
    check = False
    for j in range(0, size):
        if precheck[j] == 'c2isless' and currcheck[j] == 'c1isless':
            check = False
            break
        elif precheck[j] == 'c1isless' and currcheck[j] == 'c2isless':
            check = False
            break
        elif precheck[j] == 'bothequal' and currcheck[j] == 'c1isless':
            check = True
        elif precheck[j] == 'bothequal' and currcheck[j] == 'c2isless':
            check = True
        elif precheck[j] == 'bothequal' and currcheck[j] == 'bothequal':
            check = True
        elif precheck[j] == 'c1isless' and currcheck[j] == 'bothequal':
            check = True
        elif precheck[j] == 'c2isless' and currcheck[j] == 'bothequal':
            check = True
        elif precheck[j] == currcheck[j]:
            check = True
    df[letter + 'C' + str(1)] = c1col
    df[letter + 'C' + str(2)] = c2col 
    letter = chr(ord(letter) + 1)
    if letter == '[':
        letter = 'A'
    if check == True:
        break
    precheck = currcheck

In [10]:
df

    X  AC1  AC2  BC1  BC2  CC1  CC2  DC1  DC2  EC1  EC2  FC1  FC2  GC1  GC2
0   1    8    5    7    8    4    9    7    0    9    2    5    9    7    8
1   2    7    4    6    7    3    8    6    1    8    1    4    8    6    7
2   3    6    3    5    6    2    7    5    2    7    0    3    7    5    6
3   4    5    2    4    5    1    6    4    3    6    1    2    6    4    5
4   5    4    1    3    4    0    5    3    4    5    2    1    5    3    4
5   6    3    0    2    3    1    4    2    5    4    3    0    4    2    3
6   7    2    1    1    2    2    3    1    6    3    4    1    3    1    2
7   8    1    2    0    1    3    2    0    7    2    5    2    2    0    1
8   9    0    3    1    0    4    1    1    8    1    6    3    1    1    0
9  10    1    4    2    1    5    0    2    9    0    7    4    0    2    1